# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poked_users',
            field=models.ManyToManyField(related_name='_user_poked_users_+', to='poke.User'),
        ),
    ]
