# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_user_poked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poked_users',
            field=models.ManyToManyField(related_name='poked_by', to='poke.User'),
        ),
    ]
