# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='No Description Provided'),
        ),
    ]
