# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_books',
            field=models.ManyToManyField(related_name='liked_users', to='likes_books.User'),
        ),
    ]
