# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
